### PR TITLE
Add fix for race condition during rpm installs

### PR DESCRIPTION
**Pull request by rancher-max**
#### Proposed Changes ####

There is currently a race condition that prevents the GPG key in an rke2 install from successfully being signed in some cases.

#### Types of Changes ####

bugfix

#### Testing ####

Ran a jenkins job that was always failing previously

Checklist:
1. If your PR changes anything on or related to Jenkins, run it pointing to your branch to make sure it's okay.

2. Verify code lint; we should not have errors.

3. Update the documentation if needed.

4. Update makefile and docker run if adding new tests.

5. Run your tests at least 4 times with all configurations needed and possible.

6. If needed test with different os types.

### CODE REVIEW

**Review by VestigeJ — APPROVED** [review]

**Review by aganesh-suse — APPROVED** [review]
LGTM

**Comment by mdrahman-suse** [comment]
Do we need to add this k3s as well? @rancher-max

**Comment by rancher-max** [comment]
> Do we need to add this k3s as well, to be consistent? @rancher-max

Nope, k3s doesn't have any of this anyway so we should be fine leaving it out!

**Comment by rancher-max** [comment]
image
Success!

**Review by ShylajaDevadiga — APPROVED** [review]

**Pull request merged**
