### PR TITLE
Make kubeconfig explicit during k3s initial server check

### PR DESCRIPTION
**Pull request by rancher-max**
#### Proposed Changes ####

bugfix

#### Testing ####

Checklist:
1. If your PR changes anything on or related to Jenkins, run it pointing to your branch to make sure it's okay.

2. Verify code lint; we should not have errors.

3. Update the documentation if needed.

4. Update makefile and docker run if adding new tests.

5. Run your tests at least 4 times with all configurations needed and possible.

6. If needed test with different os types.

### CODE REVIEW

**Comment by mdrahman-suse** [comment]
Do we need to add the same for rke2?

**Review by aganesh-suse — APPROVED** [review]

**Review by endawkins — APPROVED** [review]

**Review by mdrahman-suse — COMMENTED** [review]
Also can we define a global var like `kubeconfigpath=/etc/rancher/k3s/k3s/yaml` for this so that its not repetitive?

**Comment by aganesh-suse** [comment]
> Do we need to add the same for rke2?



> Do we need to add the same for rke2?

no other shell script seems to use the kubectl command.

**Comment by rancher-max** [comment]
@mdrahman-suse RKE2 doesn't have this check here so we should be fine on that. We can define a global var but it's just three spots in this one file so I thought maybe this would be fine. I'll do whichever you prefer 😇

**Comment by mdrahman-suse** [comment]
LGTM then

**Pull request merged**
